GET http://localhost:3003/user 

###
POST http://localhost:3003/user 
Content-Type: application/json

{
    "name": "rodrigo2",
    "email": "email2@email.com",
    "password": "123456"
}
###

DELETE http://localhost:3003/user/1658953960721