GET http://localhost:3004/todoLists/all



###
GET http://localhost:3004/todoLists/554888-afs-58445/task




###
GET http://localhost:3004/todoLists/554888-afs-58445/User



###
POST http://localhost:3004/todoListUsers/create 
Content-Type: application/json


{
"name": "Rosivaldo macedo", 
"nickname": "rosivaldo", 
"email": "rosivaldo99@gmail.com"
}



###
POST http://localhost:3004/todoLists/task 
Content-Type: application/json

{
    "title": "Assistente bancário",
	"description": "Deve ajudar os velhos a tirar dinheiro no banco",
	"limitDateTask": "28/06/2022",
	"creator_user_id": "e92902af-1e7c-435e-8222-e25c19be3f33"
}



###
PUT http://localhost:3004/todoListsUser/e92902af-1e7c-435e-8222-e25c19be3f33/update
Content-Type: application/json


{
"name": "Rosivaldo macedo passo", 
"nickname": "rosilvo"
}


###