GET http://localhost:3003/post/fa3c435e-5232-4cea-9350-7b8d6a6aadaf
###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "meta",
    "email": "meta@gmail.com",
    "password": "486213"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "https://imgs.extra.com.br/55039321/1xg.jpg?imwidth=292",
    "description": "celular",
    "type": "normal",
    "authorId": "f805de7e-2e7d-4199-ae74-9cbde80e63fb"
}
###
POST http://localhost:3003/users/friend/f805de7e-2e7d-4199-ae74-9cbde80e63fb
Content-Type: application/json

{
    "friendId": "5854730a-14e4-45a8-ab4f-e1c0e6597c21"
}