GET http://localhost:3003/post/fa3c435e-5232-4cea-9350-7b8d6a6aadaf
###

GET http://localhost:3003/users/feed/f805de7e-2e7d-4199-ae74-9cbde80e63fb
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "meta4",
    "email": "meta4@gmail.com",
    "password":"38621324"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "http://staticmobly.akamaized.net/p/Rufato-Conjunto-de-Mesa-de-Jantar-com-Vidro-e-6-Cadeiras-Maia-I-Veludo-Imbuia-e-Creme-8044-849615-1-zoom.jpg",
    "description": "smart-fone",
    "type": "normal",
    "authorId": "43dcf17a-247c-4687-af6f-606f2c44b4a8"
}
###
POST http://localhost:3003/users/friend/f805de7e-2e7d-4199-ae74-9cbde80e63fb
Content-Type: application/json

{
    "friendId": "05446efda-4a0d-4009-92c7-d26106ead849"
}
###

DELETE http://localhost:3003/users/deleteFriend/62d0c690-7f57-4abf-ba95-57d5a8578d88