GET http://localhost:3003/usersAll
###

GET http://localhost:3003/usersAll?sort=name&order=desc

###
GET http://localhost:3003/productAll
###

GET http://localhost:3003/productAll?sort=name&order=desc
###

GET http://localhost:3003/purchase/74ff4538-ea07-467b-a60f-aa890a8b39b1
###

###
POST http://localhost:3003/users
Content-Type: application/json


{
    "name": "benjamin",
    "email": "benjamin@gmail.com",
    "password": "benjamin98428"
}
###

POST http://localhost:3003/productCreate
Content-Type: application/json

{
    "name": "vinicius",
    "price": 4500,
    "imageUrl": "https://images.kabum.com.br/produtos/fotos/166104/placa-de-video-zotac-nvidia-geforce-rtx-3060ti-twin-edge-lhr-8gb-14-0-gbps-gddr6-dlss-ray-tracing-zt-a30610e-10mlhr_1623326525_gg.jpg"
}

###
POST http://localhost:3003/purchases
Content-Type: application/json


{
    "userId": "34bc8987-6019-496f-af17-1abb00e3672d",
    "productId": "0d64dd34-79d3-48bb-a6ab-a337e2a88946",
    "quantity": 6
}