GET http://localhost:3003/usersAll?sort=name&order=desc
###

GET http://localhost:3003/productAll?
###

GET http://localhost:3003/purchase/34bc8987-6019-496f-af17-1abb00e3672d
###

###
POST http://localhost:3003/users
Content-Type: application/json


{
    "name": "simone",
    "email": "simone@gmail.com",
    "password": "simone68428"
}
###

POST http://localhost:3003/productCreate
Content-Type: application/json


{
    "name": "maquiagem",
    "price": 230,
    "imageUrl": "https://www.megamaquiagem.com.br/produtos/kit-de-maquiagem-com-maleta-maquiadora-completa-profissional/"
}



###
POST http://localhost:3003/purchases
Content-Type: application/json


{
    "userId": "34bc8987-6019-496f-af17-1abb00e3672d",
    "productId": "0d64dd34-79d3-48bb-a6ab-a337e2a88946",
    "quantity": 6
}